import Menu from "@/components/Menu";

export const metadata = {
  title: "Get Train Info",
  description: "Generated by create next app",
};

async function Users() {
  return (
    <div className="p-5">
      <Menu />
    </div>
  );
}

export default Users;
